### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by akiyosi** [kaakaa/matter-meeting#1]
面白いPoCだと思い、社内でデプロイを試みていますが、`docker-compose up －d` を実行すると以下のようなエラーとなり app が Exit してしまいます。同じローカルホスト上で google chrome で `http://127.0.0.1:9000/` にアクセスすると minio のサーバには正常にアクセスが可能であることは確認しました。

以下切り分け状況です。
* NO_PROXY を疑い `docker-compose.yml` の arg に no_proxy のエントリを追記しましたが状況変わらず。
* `http_proxy`, `https_proxy`  を空にしてみましたが状況は変わらず。(プロキシを空にした状態で`doocker-compose up -d --build`を実行するとdocker イメージを取得できずデプロイが進みません。)

* 設定 `default.json` の `server.host`, `minio.endPoint` を `"app"`, `"minio"` にしても同じエラーとなる。

こちらの設定において何かお気づきの不備がありましたらご指摘いただけますと幸いです。

<br>

Hi, I got the following error when I tryed to deploy matter-meeting.
Are there any additional settings in the environment?

<br>

``` docker-compose logs
app_1    | listen: 8000
app_1    | Error: connect ECONNREFUSED 127.0.0.1:9000
app_1    |     at Object._errnoException (util.js:999:13)
app_1    |     at _exceptionWithHostPort (util.js:1020:20)
app_1    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1207:14)
```

``` bash
root@ubuntu:~/matter-meeting# docker ps -a
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS                          PORTS                    NAMES
4314281b4256        mattermeeting_app    "node lib/controller…"   About a minute ago   Exited (1) About a minute ago                            mattermeeting_app_1
11a7a4ef0645        minio/minio:latest   "/usr/bin/docker-ent…"   About a minute ago   Up About a minute (healthy)     0.0.0.0:9000->9000/tcp   mattermeeting_minio_1
```
``` json
{
  "server": {
    "host": "localhost",
    "port": 8000
  },
  "ews": {
    "server": "https://hoge/ews/Exchange.asmx",
    "username": "fuga",
    "password": "fugapwd",
    "allowed_domain": ["hoge1@example.com", "hoge2@example.com", "hoge3@example.com"]
  },
  "minio": {
      "endPoint": "localhost",
      "port": 9000,
      "secure": false,
      "accessKey": "access_key",
      "secretKey": "secret_key",
      "bucket": "matter-meeting"
  }
}
```

``` yaml
version: '3'

services:
  app:
    build:
      context: .
      args:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    ports:
    - "8000:8000"
    volumes:
    - ./config/default.json:/usr/local/src/config/default.json
  minio:
    image: minio/minio:latest
    command: server /export
    environment:
    - "MINIO_ACCESS_KEY=access_key"
    - "MINIO_SECRET_KEY=secret_key"
    ports:
     - "9000:9000"
    volumes:
    - ./minio/data/export:/export
    - ./minio/data/.minio:/root/.minio
```

``` bash
root@ubuntu:~/matter-meeting# docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false
root@ubuntu:~/matter-meeting#
```

``` bash
root@ubuntu:~/matter-meeting# node -v
v9.4.0
```

**Comment by kaakaa** [comment]
エラーメッセージを見ると、docker-composeのappサービスからminioサービスが見えていないのが原因のようですね。
`docker-compose.yml`内の`app.build.args`のproxy指定はビルドプロセス時に利用される値のため無関係かと思います。

## 確認事項1: docker-composeのバージョン

手元にdocker engineのバージョンが同じlinuxサーバーがあったため、git cloneして`matter-meeting`を起動してみましたが、事象は再現しませんでした。
docker-composeのバージョンの違いによるもかも知れないので、docker-composeのバージョンも教えていただいてよろしいでしょうか

```
$ docker-compose version
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

## 確認事項2: `minio.endPoint`を変更した際のエラーログ

> 設定 default.json の server.host, minio.endPoint を "app", "minio" にしても同じエラーとなる。

`minio.endPoint`を "minio" とした場合、下記エラーログの`127.0.0.1`の部分は`minio`に変わりそうですが、変化が無いようならば`config/default.json`の修正が反映されていないかもしれません。
(`server.host`の方は"localhost"のままにしておく必要があると思います)

> app_1    | Error: connect ECONNREFUSED 127.0.0.1:9000

## 提案: `depends_on`設定の追加

手元で再現しないため確証はないですが、「appサービスからminioサービスが見えていない」という点から、appサービスの`depends_on`設定に"minio"を追加するのは如何でしょう。
(default.jsonの`minio.endPoint`は"minio"としてください)

```
...
services:
  app:
    build:
      context: .
      args:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    depends_on:
      - minio
    ports:
    - "8000:8000"
    volumes:
    - ./config/default.json:/usr/local/src/config/default.json
...
```
